Algoritmo "formatacao"


Var
n1 , n2 , res: real


Inicio

      n1 <- 1054
      n2 <- 150
      
      
      // operação
      res <- n1 / n2
      escreval(res:10:3)
      
      // explicação
      // (A : B)
      // no A, eu falo o total na frente, para o alinhamento.
      // caso eu tenha um numero maior
      
      
      // no B, eu dddescido a quantidade de casas ou numeros decimais


Fimalgoritmo