Algoritmo "desafio_1"


Var
 valor_pago: real
 valor_produto: real
 troco: real


Inicio

      // entrada
      
      escreval("digite o pago")
      leia(valor_pago)

      escreval("digite o valor do produto")
      leia(valor_produto)
      
      // processamneto
      troco <-  valor_pago -  valor_produto
      
      // saida
      escreval(" seu troco ", "R$:" , troco:2:2)









Fimalgoritmo