Algoritmo "passo_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2026
Var
espaco_guardaRoupa: caractere
nome: caractere


Inicio
escreva("olá mundo")
escreval("esse pula linha")
escreval("linha pulada")
espaco_guardaRoupa <- "Toalha"
escreval( espaco_guardaRoupa)

escreval("digite seu nome:")
leia(nome)
escreval("olá, muito prazer " + nome + "!")

Fimalgoritmo