Algoritmo "01-matrizes"

Var

mat : vetor[0..1, 0..1] de inteiro
i, j: inteiro


Inicio
// atribuição de dados
   para i de 0 ate 1 faca
        para j de 0 ate 1 faca
        escreval("escvreva o valor")
          leia(mat[i, j])
        
        fimpara
   fimpara
   
// saida de dados
   para i de 0 ate 1 faca
        para j de 0 ate 1 faca
          escreval(mat[i, j])

        fimpara
   fimpara


Fimalgoritmo