Algoritmo "01-matrizes"

Var

mat1 : vetor[0..2, 0..3] de inteiro
linha, coluna: inteiro


Inicio
// atribuição de dados
   para linha de 0 ate 2 faca
        para coluna de 0 ate 3 faca
          mat1[linha, coluna] <- 1
        
        fimpara
   fimpara
   
   // se eu quizer fazer um manuamnete
   mat1[1,2] <-800

// saida de dados
   para linha de 0 ate 2 faca
        para coluna de 0 ate 3 faca
          escreval(mat1[linha, coluna])

        fimpara
   fimpara


Fimalgoritmo